version: '2'
services:
  node1:
    build: .
    ports:
      - 3000
      - 9998
    volumes:
      - .:/code:ro
  node2:
    build: .
    ports:
      - 3000
      - 9998
    volumes:
      - .:/code:ro
    environment:
      GOSSIPER_PEERS: node1:9998
  node3:
    build: .
    ports:
      - 3000
      - 9998
    volumes:
      - .:/code:ro
    environment:
      GOSSIPER_PEERS: node1:9998,node2:9998
  #server:
  #  build: .
  #  ports:
  #    - 3000
  #    - 9998
  #  volumes:
  #    - .:/code:ro
  #test:
  #  build: .
  #  command: perl test_gossip.pl
  #  volumes:
  #    - .:/code:ro
  #  depends_on:
  #    - server
